before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem update --system 2.1.11 # do this twice because it always breaks
  - gem --version

language: ruby
rvm:
  - ruby-head
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - ree
  - jruby-18mode
  - jruby-19mode
